### ISSUE TITLE
DWR Users Monitor Development and Testing Servers

### ISSUE THREAD

**Issue by qjhart** [qjhart/spatial-cimis#9]
DWR needs to monitor the development and test servers daily operations.  Each server maintains it's operations via a [cronjob](https://github.com/qjhart/spatial-cimis/blob/master/crontab).  There are three main components:
- Daily - do some maintenance and cleanup on the satellite files.
- Every day at 4:30 (with some follow ons) run the previous days ET
- Every 30 min check for new imagery

**Comment by qjhart** [comment]
I've updated the cronjob to point to cimissupport@water.ca.gov.

**Comment by qjhart** [comment]
@ajdelmundo You should be getting emails sent to cimissupport@water.ca.gov for the GOES processing for today.  I am working on improving the output from these cronjobs (see #12 ).  If you are receiving emails, including the 4:30  am one tomorrow, then you can close this issue.

**Comment by ajdelmundo** [comment]
@qjhart I received the 4:30 am email.  Closing the issue.

Cleaning up temporary files ...
Starting GRASS ...
Executing '/apps/cimis/grass/scripts/cg.ca_daily_vis.rc' ...
Welcome to GRASS 6.4.4 (2014) 
make: Nothing to be done for `ca-daily-vis'.
Closing monitors ...
Cleaning up temporary files ...
Batch job '/apps/cimis/grass/scripts/cg.ca_daily_vis.rc' (defined in GRASS_BATCH_JOB variable) was executed.
Goodbye from GRASS GIS
